# Conversion of diameter reconstruction to biomass
# Sampling the MCMC output generated by PEcAn to obtain ranges of possible biomass as opposed to a single line
setwd("~/Dropbox/PalEON CR/Tree Rings/Tree-Rings-and-Biomass/Uncertainty_analysis/AllomFiles/March19/")
# creating an object to serve as a home for all of the allometry samples we will pull from the individual species mcmc

allometries<- list()

# Sampling 500 random rows from the last 5000 runs of the MCMC

# need to not pull rows with a negative mu1
# loading in the MCMC data from PEcAn for PIPO
load("Allom.PIPO.2.Rdata")
allometries[["pipo"]] <- mc[[3]][sample(which(mc[[3]][,"mu1"]>=0), size=500, replace=T),]

summary(allometries)
summary(allometries$pipo)

# loading in PSME pecan mcmc runs and making a PSME section within the allometries list. This will be repeate for all species present in the DOE study.
load("Allom.PSME.2.Rdata")
allometries[["psme"]] <- mc[[3]][sample(which(mc[[3]][,"mu1"]>=0), size=500, replace=T),]
summary(allometries)
summary(allometries$psme)

# loading in ABCO pecan mcmc runs
load("Allom.ABCO.2.Rdata")
allometries[["abco"]] <- mc[[3]][sample(which(mc[[3]][,"mu1"]>=0), size=500, replace=T),]
summary(allometries)
summary(allometries$abco)


# loading in general spruce pecan mcmc runs
load("Allom.picea.sp.2.Rdata")
allometries[["picea.sp"]] <- mc[[3]][sample(which(mc[[3]][,"mu1"]>=0), size=500, replace=T),]
summary(allometries)
summary(allometries$picea.sp)

# loading in general pine pecan mcmc runs
load("Allom.pinus.sp.2.Rdata")
allometries[["pinus.sp"]] <- mc[[3]][sample(which(mc[[3]][,"mu1"]>=0), size=500, replace=T),]
summary(allometries)
summary(allometries$pinus.sp)

# loading in general fir pecan mcmc runs
load("Allom.abies.sp.2.Rdata")
allometries[["abies.sp"]] <- mc[[3]][sample(which(mc[[3]][,"mu1"]>=0), size=500, replace=T),]
summary(allometries)
summary(allometries$abies.sp)


#save the list as ______ to draw from later when we convert diameter reconstructions into biomass
save(allometries, file="allometries_list.Rdata")
