#setwd("~/Dropbox/PalEON CR/Tree Rings/Tree-Rings-and-Biomass/Uncertainty_analysis")

library(dplR)
library(ggplot2)
se <- function(x){
  sd(x, na.rm=TRUE) / sqrt((length(!is.na(x))))}
# Run this script after the gap filling process scripts have been run
# For the NACP15 abstract run Tree_rw_gapfilled.csv


# load in the diameter reconstructions generated by Christy.  These are based upon gapfilled tree ring data using the fancy model.

g.filled.diam <- read.csv("GapFilling_DBHrecon_ALL.csv", header=T, row.names=1)
g.filled.diam <- g.filled.diam[,substr(names(g.filled.diam),1,1)=="V"]
summary(g.filled.diam)

# read in tree data
tree.data <- read.csv("TreeData.csv", header=T)
summary(tree.data)
#trees.use <- tree.data[substr(tree.data$PlotID, 1, 1)=="V" | substr(tree.data$PlotID, 1, 2)=="MM",]
trees.use <- tree.data[substr(tree.data$PlotID, 1, 1)=="V" & tree.data$Dated=="Y",]
trees.use <- trees.use[!is.na(trees.use$TreeID),]
head(trees.use)
dim(trees.use)

summary(trees.use[substr(trees.use$PlotID, 1, 2)=="VU",])
summary(trees.use[substr(trees.use$PlotID, 1, 2)=="VL",])

#making g.filled.diam the same length as tree.data
g.filled.diam <- g.filled.diam[,substr(names(g.filled.diam),1,1)=="V" & names(g.filled.diam) %in% trees.use$TreeID]
dim(g.filled.diam)

summary(trees.use)

#quick plot
#spag.plot(g.filled.diam)

plot.data <- read.csv("raw input files/DOE_plus_Valles.csv")
summary(plot.data)


##########################################################################
# Allometric Equations
##########################################################################


#Convert to biomass with the allometric equation
#using the PECAN generated bayesian equations
library(car)
load("allometries_list.Rdata")

# Getting rid of POTR for now for conceptual figure purposes
#trees.use <- trees.use[!(trees.use$Species=="POTR"),]
summary(trees.use)
unique(trees.use$Species)

trees.use$spp.allom <- recode(trees.use$Species, " 'PIEN'='picea.sp'; 'PIPO'='pipo'; 'PSME'='psme'; 'POTR' = 'potr'")
summary(trees.use)
plots <- unique(trees.use$PlotID) # You had the right idea, but it was throwing errors because you were trying to evaluate plots you haven't gotten to yet



# will want to do general equations and pft level equations as well, but later
# log(AGB) = mu0 + mu1*log(DBH) --equaton form of PECAN allometrics

#allom.eq <- function(mu0, mu1, DBH) { mu0 * DBH^mu1}
allom.eq <- function(mu0, mu1, DBH) { exp(mu0 + mu1 * log(DBH) )}

# dbh <- 1:50
# test <- allom.eq(mu0= -3.5185,
#                  mu1 = 2.6909,
#                  DBH = dbh)
# 
# plot(test*.09 ~ dbh)

allom.temp <- g.filled.diam
allom.temp[,] <- NA

# dbh=0 causes problems, so we're going to make those NA
g.filled.diam[g.filled.diam==0] <- 1e-6
min(g.filled.diam, na.rm=T)
summary(g.filled.diam)
dim(g.filled.diam)

bm.array <- array(NA, dim=c(nrow(g.filled.diam), length(unique(trees.use$PlotID)), nrow(allometries[[1]])))
row.names(bm.array) <- row.names(g.filled.diam)  #CRR Added
dimnames(bm.array)[[2]] <- unique(trees.use$PlotID)
summary(bm.array[,,1])
#--------------------------------------------------
# INSERT i LOOP HERE to go through each iteration of randomness from MCMC
# This is one big loop that goes through each layer of the 500 iterations
#--------------------------------------------------
for(i in 1:nrow(allometries[[1]])){
  allom.temp <- g.filled.diam
  allom.temp[,] <- NA
  
  # Species loop for calculating tree biomass
  for(j in unique(trees.use$spp.allom)){
    cols <- which(names(g.filled.diam) %in% trees.use[trees.use$spp.allom==j, "TreeID"])
    # Note: we'll have to make this a bit fancier in the future for species with mu0==0
    #   allom.temp[,cols] <- allom.eq(mu0= -3.5185,
    #                          mu1 = 2.6909,
    #                         #DBH = seq(from=30, to=1, length=nrow(g.filled.diam)))
    #                          DBH = g.filled.diam[,cols])
    # test <- allom.eq(mu0=ifelse(!(allometries[[j]][i,"mu0"]==0 & allometries[[j]][i,"mu1"]==0),allometries[[j]][i,"mu0"], allometries[[j]][i,"Bg0"]),
    #                               mu1 =ifelse(!(allometries[[j]][i,"mu0"]==0 & allometries[[j]][i,"mu1"]==0),allometries[[j]][i,"mu1"], allometries[[j]][i,"Bg1"]),
    #                               DBH = g.filled.diam[,cols])
    # mu0 = ifelse(!(allometries[[j]][i,"mu0"]==0 & allometries[[j]][i,"mu1"]==0),allometries[[j]][i,"mu0"], allometries[[j]][i,"Bg0"])
    # mu1 = ifelse(!(allometries[[j]][i,"mu0"]==0 & allometries[[j]][i,"mu1"]==0),allometries[[j]][i,"mu1"], allometries[[j]][i,"Bg1"])
    mu0=allometries[[j]][i,"Bg0"]
    mu1=allometries[[j]][i,"Bg1"]
    allom.temp[,cols] <- allom.eq(mu0=mu0, mu1 = mu1, DBH = g.filled.diam[,cols])
  }
  # summing to the plot level
  
  allom.temp[is.na(allom.temp)] <- 0
  
  # biomass loop for summing trees to plots
  # We're doing the unit conversions here; we had calculated density in stems/ha, but Christy wants to look at Biomass in kg/m2, so we're putting everything in kg/m2 here
  for(p in 1:length(plots)){
    cols <- which(names(allom.temp) %in% trees.use[trees.use$PlotID==plots[p], "TreeID"])
    if(substr(plots[p],1,1)=="V"){
      bm.array[,p,i] <- rowMeans(allom.temp[,cols])*plot.data[plot.data$PlotID==paste(plots[p]), "Density.Total..stems.ha."]/10000 #mean tree * trees/ha (do for Valles only bc sum of trees != plot density; different sampling method than Neil)
    } else {
      temp <- allom.temp[,cols]
      for(n in names(temp)){ # Convert biomass/tree to biomass/ha
        temp[,n] <- temp[,n] * tree.data[tree.data$TreeID==t,"Density..stems.ha."]/10000
      }
      bm.array[,p,i] <- rowSums(temp) #sum biomass/ha
    }
  }
}
#--------------------------------------------------

#bm.array[,,1]
summary(bm.array[,,1])

# OFFENDER: VUF032; VUF026 is good
g.filled.diam[,c("VUF026","VUF032")]

### OUTSIDE of all LOOPs (iteration + species + plots)
# You should now have a 3-dimensional array with plots as columns, years as rows, and iterations as layers

biom.mean <- apply(bm.array[,,], c(1,2), mean) # bm.array==the array you're working with, 3 = do the funciton to the layers (3rd dim), mean = the function you're running
biom.ci <- apply(bm.array[,,], c(1,2), quantile, c(0.025, 0.975)) # bm.array==the array you're working with, 3 = do the funciton to the layers (3rd dim), mean = the function you're running
# biom.se <- apply(bm.array[,,], c(1,2), se)

biom.mean <- as.data.frame(biom.mean)
names(biom.mean)<- paste(plots, c("70%", "82%", "82%", "90%"),"Dated", sep=".")

biom.lbound <- data.frame(biom.ci[1,,])
names(biom.lbound) <- paste(plots, "LB", c(), "Dated", sep=".")
biom.ubound <- data.frame(biom.ci[2,,])
names(biom.ubound) <- paste(plots, "UB", "Dated", sep=".")
# biom.ci <-as.data.frame(biom.ci)
# names(biom.ci)<- c(paste(plots, "sd", sep="."))
# biom.se <-as.data.frame(biom.se)
# names(biom.se)<- c(paste(plots, "se", sep="."))




biom.valles.dated <- as.data.frame(c(biom.mean, biom.lbound, biom.ubound))
row.names(biom.valles.dated) <- row.names(biom.mean)
summary(biom.valles.dated)
head(biom.valles.dated)

save(biom.valles.dated, file="valles_bm_recon_Dated_only.Rdata")
#save(biom.valles.dated, file="biom.valles.dated_cum.csv")

#---------------------------------------------------------------------
# This we did in a loop above to make it mroe flexible for the future
# (and we did it right this time)
#---------------------------------------------------------------------
# biom.valles.dated.cum.dens <- biom.valles.dated
# 
# biom.valles.dated.cum.dens$VLA <- biom.valles.dated.cum.dens$VLA / 144/1000
# biom.valles.dated.cum.dens$VLA.ci <- biom.valles.dated.cum.dens$VLA.ci /144/1000
# biom.valles.dated.cum.dens$VLA.se <- biom.valles.dated.cum.dens$VLA.se /144/1000
# 
# biom.valles.dated.cum.dens$VLB <- biom.valles.dated.cum.dens$VLB /624/1000
# biom.valles.dated.cum.dens$VLB.ci <- biom.valles.dated.cum.dens$VLB.ci /624/1000
# biom.valles.dated.cum.dens$VLB.se <- biom.valles.dated.cum.dens$VLB.se /624/1000
# 
# biom.valles.dated.cum.dens$VUA <- biom.valles.dated.cum.dens$VUA /576/1000
# biom.valles.dated.cum.dens$VUA.ci <- biom.valles.dated.cum.dens$VUA.ci /576/1000
# biom.valles.dated.cum.dens$VUA.se <- biom.valles.dated.cum.dens$VUA.se /576/1000
# 
# biom.valles.dated.cum.dens$VUB <- biom.valles.dated.cum.dens$VUB /576/1000
# biom.valles.dated.cum.dens$VUB.ci <- biom.valles.dated.cum.dens$VUB.ci /576/1000
# biom.valles.dated.cum.dens$VUB.se <- biom.valles.dated.cum.dens$VUB.se /576/1000
# 
# summary(biom.valles.dated.cum.dens)
# biom.valles.dated.cum.dens$year <- as.factor(row.names(biom.valles.dated.cum.dens))
# head(biom.valles.dated.cum.dens)

# now we have biomass per m^2 for each plot with SD
#---------------------------------------------------------------------

#save(biom.valles.dated.cum.dens, file="biom_valles_dum_m2.csv")

biom.valles.dated.stack <- stack(biom.valles.dated[1:4])
names(biom.valles.dated.stack) <- c("Biom.Mean", "PlotID")
biom.valles.dated.stack$Year <- as.numeric(paste(row.names(biom.valles.dated)))
biom.valles.dated.stack$Plot <- as.factor(substr(biom.valles.dated.stack$PlotID, 3,3))
biom.valles.dated.stack$Site <- as.factor(substr(biom.valles.dated.stack$PlotID, 1,2))
summary(biom.valles.dated.stack)

biom.valles.dated.stack.lb <- stack(biom.valles.dated[5:8])
names(biom.valles.dated.stack.lb) <- c("Biom.LB", "PlotID")

biom.valles.dated.stack.ub <- stack(biom.valles.dated[9:12])
names(biom.valles.dated.stack.ub) <- c("Biom.UB", "PlotID")

biom.valles.dated.stack$Biom.LB <- biom.valles.dated.stack.lb[,1]
biom.valles.dated.stack$Biom.UB <- biom.valles.dated.stack.ub[,1]
summary(biom.valles.dated.stack)

# biom.valles.stack$Ribbon.max <- biom.valles.stack$Biom.Mean + biom.valles.stack$Biom.ci
# biom.valles.stack$Ribbon.min <- biom.valles.stack$Biom.Mean - biom.valles.stack$Biom.ci
# biom.valles.stack$Ribbon.min <- ifelse(biom.valles.stack$Ribbon.min < 0, 0, biom.valles.stack$Ribbon.min)
# biom.valles.stack$Ribbon.max <- ifelse(biom.valles.stack$Ribbon.max > 100, 100, biom.valles.stack$Ribbon.max)
summary(biom.valles.dated.stack)

save(biom.valles.dated.stack, file="valles_bm_recon_stack_DatedONLY.Rdata")
load("valles_bm_recon_stack.Rdata")

valles.composite.stack <- rbind(biom.valles.dated.stack, biom.valles.stack)
summary(valles.composite.stack)

library(ggplot2)

ggplot(data=valles.composite.stack[valles.composite.stack$Year<2012 & (valles.composite.stack$Site=="VL"),])  + facet_grid(Plot ~ Site) +
    
  # plotting total site basal area  
  geom_ribbon(aes(x=Year, ymin=Biom.LB, ymax=Biom.UB, fill=PlotID), alpha=0.5) +
  geom_line(aes(x=Year, y=Biom.Mean, color=PlotID)) +
  ggtitle("Valles Caldera Lower (PIPO)")

ggplot(data=valles.composite.stack[valles.composite.stack$Year<2012 & (valles.composite.stack$Site=="VU"),])  + facet_grid(Plot ~ Site) +
  #ggplot(data=valles.composite.stack[valles.composite.stack$Year<2012 & (valles.composite.stack$PlotID=="VUB"),])  + facet_grid(Plot ~ Site) +
  # plotting total site basal area  
  geom_ribbon(aes(x=Year, ymin=Biom.LB, ymax=Biom.UB, fill=PlotID), alpha=0.5) +
  geom_line(aes(x=Year, y=Biom.Mean, color=PlotID)) +
  ggtitle("Valles Caldera Upper (MCON)")



# valles.cum.plot<- 
#pdf("Valles_Biomass_19March_Christy_ChojnackyOnly.pdf", height=8.5, width=11)
ggplot(data=valles.composite.stack[valles.composite.stack$Year<2012,])  + facet_grid(Plot ~ Site) +
  # plotting total site basal area  
  geom_ribbon(aes(x=Year, ymin=Biom.LB, ymax=Biom.UB, fill=PlotID), alpha=0.5) +
  geom_line(aes(x=Year, y=Biom.Mean, color=PlotID)) +
  ggtitle("Dated vs. Dated_plus_modeled")

#   theme(axis.line=element_line(color="black", size=0.5), panel.grid.major=element_blank(), panel.grid.minor= element_blank(), panel.border= element_blank(), panel.background= element_blank(), axis.text.x=element_text(angle=0, color="black", size=12), axis.text.y=element_text(color="black", size=12))+
#   scale_fill_discrete(name="Model", labels = c("nt.pipo.mean", "nt.piaz.mean", "nt.pine.spp", "nt.vcnp.mean", "nt.pine.dom.mean")))
# dev.off()

