#setwd("~/Dropbox/PalEON CR/Tree Rings/Tree-Rings-and-Biomass/Uncertainty_analysis")
library(dplR)
library(ggplot2)
se <- function(x){
  sd(x, na.rm=TRUE) / sqrt((length(!is.na(x))))}
# Run this script after the gap filling process scripts have been run
# For the NACP15 abstract run Tree_rw_gapfilled.csv


# load in the diameter reconstructions generated by Christy.  These are based upon gapfilled tree ring data using the fancy model.

g.filled.diam <- read.csv("Gapfilling_DBHrecon_Litvak.csv", header=T, row.names=1)
g.filled.diam[is.na(g.filled.diam)] <- 0
#g.filled.diam <- g.filled.diam[,!names(g.filled.diam)=="X476"]
summary(g.filled.diam[,1:10])

# read in tree data
marcy.ppine <- read.csv("raw input files/marcy_ppine_2013.csv")
summary(marcy.ppine)
marcy.mcon <- read.csv("raw input files/marcy_mcon_2012.csv")
summary(marcy.mcon)

names(marcy.ppine)
names(marcy.mcon)

# Merging the two into 1 data frame and doing a bit of formatting
marcy <- rbind(marcy.ppine[,names(marcy.ppine) %in%  names(marcy.mcon)], marcy.mcon)
# marcy$PlotID <- as.factor(paste(substr(marcy$Site, 1,3), marcy$Transect, sep="."))
marcy$PlotID <- as.factor(paste(substr(marcy$Site, 1,3), marcy$Plot_Name, sep="."))
names(marcy)[16] <- "DBH..cm." 
marcy$Tree_Tag_Number <- as.factor(paste0("X", marcy$Tree_Tag_Number))
#marcy <- marcy[!marcy$Tree_Tag_Number=="X476",]
summary(marcy)

#### ------------
marcy.density <- aggregate(marcy[,c("Plot_Radius")], by=list(marcy[,"PlotID"]), FUN=length)
names(marcy.density) <- c("PlotID", "n.stems")
marcy.density$Density.Total..stems.m2. <- marcy.density$n.stems/(pi*10^2)
summary(marcy.density)

# Merging the plot densities back into marcy's data
marcy <- merge(marcy, marcy.density)
summary(marcy)

dim(marcy)
sum(marcy.density$n.stems)

##########################################################################
# Allometric Equations
##########################################################################


#Convert to biomass with the allometric equation
#using the PECAN generated bayesian equations
library(car)

# Getting rid of POTR for now for conceptual figure purposes
#marcy <- marcy[!(marcy$Species=="POTR"),]
summary(marcy)
unique(marcy$Species)
load("allometries_list.Rdata")

marcy$spp.allom <- recode(marcy$Species, " 'PIEN'='picea.sp'; 'PIPO'='pipo'; 'ABLA'='abies.sp'; 'ABCO'='abco'; 'POTR'='potr'")
summary(marcy)
plots <- unique(marcy$PlotID) # You had the right idea, but it was throwing errors because you were trying to evaluate plots you haven't gotten to yet


# will want to do general equations and pft level equations as well, but later
# log(AGB) = mu0 + mu1*log(DBH) --equaton form of PECAN allometrics

#allom.eq <- function(mu0, mu1, DBH) { mu0 * DBH^mu1}
allom.eq <- function(mu0, mu1, DBH) { exp(mu0 + mu1 * log(DBH) )}

# dbh <- 1:50
# test <- allom.eq(mu0= -3.5185,
#                  mu1 = 2.6909,
#                  DBH = dbh)
# 
# plot(test*.09 ~ dbh)

allom.temp <- g.filled.diam
allom.temp[,] <- NA

# dbh=0 causes problems, so we're going to make those NA
g.filled.diam[g.filled.diam==0] <- 1e-6
min(g.filled.diam, na.rm=T)
summary(g.filled.diam)
dim(g.filled.diam)

bm.array <- array(NA, dim=c(nrow(g.filled.diam), length(unique(marcy$PlotID)), nrow(allometries[[1]])))
row.names(bm.array) <- row.names(g.filled.diam)  #CRR Added
dimnames(bm.array)[[2]] <- unique(marcy$PlotID)
summary(bm.array[,,1])
#--------------------------------------------------
# INSERT i LOOP HERE to go through each iteration of randomness from MCMC
# This is one big loop that goes through each layer of the 500 iterations
#--------------------------------------------------
for(i in 1:nrow(allometries[[1]])){
  allom.temp <- g.filled.diam
  allom.temp[,] <- NA
  
  # Species loop for calculating tree biomass
  for(j in unique(marcy$spp.allom)){
    cols <- which(names(g.filled.diam) %in% marcy[marcy$spp.allom==j, "Tree_Tag_Number"])
    # Note: we'll have to make this a bit fancier in the future for species with mu0==0
    #   allom.temp[,cols] <- allom.eq(mu0= -3.5185,
    #                          mu1 = 2.6909,
    #                         #DBH = seq(from=30, to=1, length=nrow(g.filled.diam)))
    #                          DBH = g.filled.diam[,cols])
    # test <- allom.eq(mu0=ifelse(!(allometries[[j]][i,"mu0"]==0 & allometries[[j]][i,"mu1"]==0),allometries[[j]][i,"mu0"], allometries[[j]][i,"Bg0"]),
    #                               mu1 =ifelse(!(allometries[[j]][i,"mu0"]==0 & allometries[[j]][i,"mu1"]==0),allometries[[j]][i,"mu1"], allometries[[j]][i,"Bg1"]),
    #                               DBH = g.filled.diam[,cols])
    # mu0 = ifelse(!(allometries[[j]][i,"mu0"]==0 & allometries[[j]][i,"mu1"]==0),allometries[[j]][i,"mu0"], allometries[[j]][i,"Bg0"])
    # mu1 = ifelse(!(allometries[[j]][i,"mu0"]==0 & allometries[[j]][i,"mu1"]==0),allometries[[j]][i,"mu1"], allometries[[j]][i,"Bg1"])
    mu0=allometries[[j]][i,"Bg0"]
    mu1=allometries[[j]][i,"Bg1"]
    allom.temp[,cols] <- allom.eq(mu0=mu0, mu1 = mu1, DBH = g.filled.diam[,cols])
  }
  # summing to the plot level
  
  allom.temp[is.na(allom.temp)] <- 0
  
  # biomass loop for summing trees to plots
  # We're doing the unit conversions here; we had calculated density in stems/ha, but Christy wants to look at Biomass in kg/m2, so we're putting everything in kg/m2 here
  for(p in 1:length(plots)){
    cols <- which(names(allom.temp) %in% marcy[marcy$PlotID==plots[p], "Tree_Tag_Number"])
    if(substr(plots[p],1,1)=="V"){
      bm.array[,p,i] <- rowMeans(allom.temp[,cols])*marcy[marcy$PlotID==paste(plots[p], na.rm=T), "Density.Total..stems.ha."]/10000 #mean tree * trees/ha (do for Valles only bc sum of trees != plot density; different sampling method than Neil)
    } else {
      temp <- allom.temp[,cols]
      for(n in names(temp)){ # Convert biomass/tree to biomass/m2
        #temp[,n] <- temp[,n] * mean(marcy[marcy$Tree_Tag_Number==n & marcy$PlotID==plots[p],"Density.Total..stems.m2."])
        temp[,n] <- temp[,n] / (pi*10^2) 
      }
      bm.array[,p,i] <- rowSums(temp) #sum biomass/m2
    }
  }
}
#--------------------------------------------------

#bm.array[,,1]
summary(bm.array[,,1])

### OUTSIDE of all LOOPs (iteration + species + plots)
# You should now have a 3-dimensional array with plots as columns, years as rows, and iterations as layers
biom.mean <- apply(bm.array[,,], c(1,2), mean) # bm.array==the array you're working with, 3 = do the funciton to the layers (3rd dim), mean = the function you're running
biom.ci <- apply(bm.array[,,], c(1,2), quantile, c(0.025, 0.975)) # bm.array==the array you're working with, 3 = do the funciton to the layers (3rd dim), mean = the function you're running
# biom.se <- apply(bm.array[,,], c(1,2), se)

biom.mean <- as.data.frame(biom.mean)
names(biom.mean)<- plots

biom.lbound <- data.frame(biom.ci[1,,])
names(biom.lbound) <- paste(plots, "LB", sep=".")
biom.ubound <- data.frame(biom.ci[2,,])
names(biom.ubound) <- paste(plots, "UB", sep=".")
# biom.ci <-as.data.frame(biom.ci)
# names(biom.ci)<- c(paste(plots, "sd", sep="."))
# biom.se <-as.data.frame(biom.se)
# names(biom.se)<- c(paste(plots, "se", sep="."))


biom.marcy <- as.data.frame(c(biom.mean, biom.lbound, biom.ubound))
row.names(biom.marcy) <- row.names(biom.mean)
summary(biom.marcy)
head(biom.marcy)
save(biom.marcy, file="marcy_bm_recon.Rdata")

#save(biom.marcy, file="biom.marcy_cum.csv")

#---------------------------------------------------------------------
# This we did in a loop above to make it mroe flexible for the future
# (and we did it right this time)
#---------------------------------------------------------------------
# biom.marcy.cum.dens <- biom.marcy
# 
# biom.marcy.cum.dens$VLA <- biom.marcy.cum.dens$VLA / 144/1000
# biom.marcy.cum.dens$VLA.ci <- biom.marcy.cum.dens$VLA.ci /144/1000
# biom.marcy.cum.dens$VLA.se <- biom.marcy.cum.dens$VLA.se /144/1000
# 
# biom.marcy.cum.dens$VLB <- biom.marcy.cum.dens$VLB /624/1000
# biom.marcy.cum.dens$VLB.ci <- biom.marcy.cum.dens$VLB.ci /624/1000
# biom.marcy.cum.dens$VLB.se <- biom.marcy.cum.dens$VLB.se /624/1000
# 
# biom.marcy.cum.dens$VUA <- biom.marcy.cum.dens$VUA /576/1000
# biom.marcy.cum.dens$VUA.ci <- biom.marcy.cum.dens$VUA.ci /576/1000
# biom.marcy.cum.dens$VUA.se <- biom.marcy.cum.dens$VUA.se /576/1000
# 
# biom.marcy.cum.dens$VUB <- biom.marcy.cum.dens$VUB /576/1000
# biom.marcy.cum.dens$VUB.ci <- biom.marcy.cum.dens$VUB.ci /576/1000
# biom.marcy.cum.dens$VUB.se <- biom.marcy.cum.dens$VUB.se /576/1000
# 
# summary(biom.marcy.cum.dens)
# biom.marcy.cum.dens$year <- as.factor(row.names(biom.marcy.cum.dens))
# head(biom.marcy.cum.dens)

# now we have biomass per m^2 for each plot with SD
#---------------------------------------------------------------------

#save(biom.marcy.cum.dens, file="biom_valles_dum_m2.csv")

biom.marcy.stack <- stack(biom.marcy[1:8])
names(biom.marcy.stack) <- c("Biom.Mean", "PlotID")
biom.marcy.stack$Year <- as.numeric(paste(row.names(biom.marcy)))
biom.marcy.stack$Plot <- as.factor(substr(biom.marcy.stack$PlotID, 5,5))
biom.marcy.stack$Site <- as.factor(substr(biom.marcy.stack$PlotID, 1,3))
summary(biom.marcy.stack)

biom.marcy.stack.lb <- stack(biom.marcy[9:16])
names(biom.marcy.stack.lb) <- c("Biom.LB", "PlotID")

biom.marcy.stack.ub <- stack(biom.marcy[17:24])
names(biom.marcy.stack.ub) <- c("Biom.UB", "PlotID")

biom.marcy.stack$Biom.LB <- biom.marcy.stack.lb[,1]
biom.marcy.stack$Biom.UB <- biom.marcy.stack.ub[,1]
summary(biom.marcy.stack)

save(biom.marcy.stack, file="marcy_bm_recon_stack.Rdata")

# biom.marcy.stack$Ribbon.max <- biom.marcy.stack$Biom.Mean + biom.marcy.stack$Biom.ci
# biom.marcy.stack$Ribbon.min <- biom.marcy.stack$Biom.Mean - biom.marcy.stack$Biom.ci
# biom.marcy.stack$Ribbon.min <- ifelse(biom.marcy.stack$Ribbon.min < 0, 0, biom.marcy.stack$Ribbon.min)
# biom.marcy.stack$Ribbon.max <- ifelse(biom.marcy.stack$Ribbon.max > 100, 100, biom.marcy.stack$Ribbon.max)
summary(biom.marcy.stack)

ggplot(data=biom.marcy.stack[biom.marcy.stack$Year<2012 & (biom.marcy.stack$Site=="PPI"),])  + facet_grid(Plot ~ Site) +
  # plotting total site basal area  
  geom_ribbon(aes(x=Year, ymin=Biom.LB, ymax=Biom.UB, fill=PlotID), alpha=0.5) +
  geom_line(aes(x=Year, y=Biom.Mean, color=PlotID)) +
  ggtitle("Valles Caldera Lower (PIPO)")

ggplot(data=biom.marcy.stack[biom.marcy.stack$Year<2012 & (biom.marcy.stack$Site=="MCO"),])  + facet_grid(Plot ~ Site) +
  #ggplot(data=biom.marcy.stack[biom.marcy.stack$Year<2012 & (biom.marcy.stack$PlotID=="VUB"),])  + facet_grid(Plot ~ Site) +
  # plotting total site basal area  
  geom_ribbon(aes(x=Year, ymin=Biom.LB, ymax=Biom.UB, fill=PlotID), alpha=0.5) +
  geom_line(aes(x=Year, y=Biom.Mean, color=PlotID)) +
  ggtitle("Valles Caldera Upper (MCON)")



# valles.cum.plot<- 
#pdf("Valles_Biomass_19March_Christy_ChojnackyOnly.pdf", height=8.5, width=11)
ggplot(data=biom.marcy.stack[biom.marcy.stack$Year<2012,])  + facet_grid(Plot ~ Site) +
  # plotting total site basal area  
  geom_ribbon(aes(x=Year, ymin=Biom.LB, ymax=Biom.UB, fill=PlotID), alpha=0.5) +
  geom_line(aes(x=Year, y=Biom.Mean, color=PlotID)) 
#   theme(axis.line=element_line(color="black", size=0.5), panel.grid.major=element_blank(), panel.grid.minor= element_blank(), panel.border= element_blank(), panel.background= element_blank(), axis.text.x=element_text(angle=0, color="black", size=12), axis.text.y=element_text(color="black", size=12))+
#   scale_fill_discrete(name="Model", labels = c("nt.pipo.mean", "nt.piaz.mean", "nt.pine.spp", "nt.vcnp.mean", "nt.pine.dom.mean")))
# dev.off()

